place = ['Tokyo', 'Paris', 'New York', 'London', 'Sydney']
print(f"Original list: {place}")
print(f"Temporary sorted list: {sorted(place)}")
print(f"Original list: {place}")
print(f"Temporary reverse sorted list: {sorted(place, reverse=True)}")
print(f"Original list: {place}")
place.reverse()
print(f"Reversing: {place}")
place.reverse()
print(f"Reversing again: {place}")
place.sort()
print(f"Sorting: {place}")
place.sort(reverse=True)
print(f"Reverse sorting: {place}")