languages = ["spanish", "french", "german", "italian", "portuguese"]
cities = ["paris", "berlin", "rome", "madrid", "lisbon"]
guests = ["alice", "brian", "colin", "david", "eve"]
print(f"\tOriginal lists: \n{languages} \n{cities} \n{guests}")
languages.sort()
cities.sort()
guests.sort()
print(f"\n\tSorted lists: \n{languages} \n{cities} \n{guests}")
message = "Hey, {guest}, would you like a souvenier from {city}? I'll also be bringing back a {language} phrasebook for you!"
print(f"\n{message.format(guest=guests[0].title(), city=cities[0].title(), language=languages[0].title())}")
print(message.format(guest=guests[1].title(), city=cities[1].title(), language=languages[1].title()))
print(message.format(guest=guests[2].title(), city=cities[2].title(), language=languages[2].title()))
print(message.format(guest=guests[3].title(), city=cities[3].title(), language=languages[3].title()))
print(message.format(guest=guests[4].title(), city=cities[4].title(), language=languages[4].title()))
popped_guest = guests.pop()
popped_language = languages.pop()
popped_city = cities.pop()
print(f"\nPopped guest: {popped_guest.title()}")
print(f"Updated guests list: {guests}")
print(f"Popped language: {popped_language.title()}")
print(f"Updated languages list: {languages}")
print(f"Popped city: {popped_city.title()}")
print(f"Updated cities list: {cities}")
message_popped = "Hey, {guest}, I'm sorry to inform you that I won't be able to bring back a souvenier from {city} or a {language} phrasebook for you."
print(f"\n{message_popped.format(guest=popped_guest.title(), city=popped_city.title(), language=popped_language.title())}")
languages.insert(0, "japanese")
cities.insert(0, "tokyo")
guests.insert(0, "frank")
print(f"\n\tUpdated lists after inserting new items: \n{languages} \n{cities} \n{guests}")
languages.append("korean")
cities.append("seoul")
guests.append("grace")
print(f"\n\tUpdated lists after appending new items: \n{languages} \n{cities} \n{guests}")
languages.reverse()
cities.reverse()
guests.reverse()
print(f"\n\tReversed lists: \n{languages} \n{cities} \n{guests}")
languages.remove("german")
cities.remove("berlin")
guests.remove("colin")
print(f"\n\tUpdated lists after removing items: \n{languages} \n{cities} \n{guests}")
print(f"\n\tFinal sorted lists: \n{sorted(languages)} \n{sorted(cities)} \n{sorted(guests)}")
print(f"\n{message.format(guest=guests[0].title(), city=cities[0].title(), language=languages[0].title())}")
print(f"{message.format(guest=guests[1].title(), city=cities[1].title(), language=languages[1].title())}")
print(f"{message.format(guest=guests[2].title(), city=cities[2].title(), language=languages[2].title())}")
print(f"{message.format(guest=guests[3].title(), city=cities[3].title(), language=languages[3].title())}")
print(f"{message.format(guest=guests[4].title(), city=cities[4].title(), language=languages[4].title())}")
print(f"\nGuests list number: {len(guests)}")
del guests[0]
print(f"\nUpdated guests list: {guests}")
del languages[0]
print(f"Updated languages list: {languages}")
del cities[0]
print(f"Updated cities list: {cities}")
print(f"\nGuests: {len(guests)}, Languages: {len(languages)}, Cities: {len(cities)}")
print(f"\n{message.format(guest=guests[0].title(), city=cities[0].title(), language=languages[0].title())}")
print(f"{message.format(guest=guests[1].title(), city=cities[1].title(), language=languages[1].title())}")
print(f"{message.format(guest=guests[2].title(), city=cities[2].title(), language=languages[2].title())}")
print(f"{message.format(guest=guests[3].title(), city=cities[3].title(), language=languages[3].title())}")